### ISSUE TITLE
Potential bug in semantic mapping module

### ISSUE THREAD

**Issue by srama2512** [facebookresearch/home-robot#452]
## 🐛 Bug

It looks like the camera poses used when updating the local map are the same across all time-steps [here](https://github.com/facebookresearch/home-robot/blob/1f393f3a244af023684668539d075e7acabde774/src/home_robot/home_robot/mapping/semantic/categorical_2d_semantic_map_module.py#L256-L262). `seq_camera_poses` must have a different value for each time, right? This could have gone unreported because the `sequence_length` was 1 in prior use cases.

Please correct me if the I'm misinterpreting the semantics of camera poses here.

## Expected behavior

The semantics of `seq_camera_poses` must be changed in the argument [here](https://github.com/facebookresearch/home-robot/blob/1f393f3a244af023684668539d075e7acabde774/src/home_robot/home_robot/mapping/semantic/categorical_2d_semantic_map_module.py#L185-L186) to be `(batch_size, sequence_length, 4, 4)` and the line [here](https://github.com/facebookresearch/home-robot/blob/1f393f3a244af023684668539d075e7acabde774/src/home_robot/home_robot/mapping/semantic/categorical_2d_semantic_map_module.py#L261) must access `seq_camera_poses[t]`.

**Comment by yvsriram** [comment]
Looking at this now.

> Our heuristic baselines would not function if this was the case

Yes, as @srama2512 mentioned we are using one-step observations in our baseline (and other use cases): https://github.com/facebookresearch/home-robot/blob/e4149d5d32c9735043a7efc49c377337a6bdb678/src/home_robot/home_robot/agent/objectnav_agent/objectnav_agent.py#L224

This one-step observation (of current step) does change across timesteps - so our baseline and prior use cases work fine.

The issue arises when a sequence of observations is passed at once. The fix is simple - I will make the change and create a PR.
