### ISSUE TITLE
New episode generator

### ISSUE THREAD

**Issue by cxzohain** [facebookresearch/home-robot#471]
Hi, Is there a way to generate a new episode but with the specific `goal_object` and `receptacles`. E.g. `goal_object:cup, start_receptacle:counter, goal_receptacle: stool`

**Comment by yvsriram** [comment]
Hey! If I understand you correctly, you are trying to filter episodes by the category of goal object, start receptacle and target receptacle (and not trying to generate new episodes).

You can first identify the episode ids using

```
import json, gzip
episodes = json.load(gzip.open('data/datasets/ovmm/val/episodes.json.gz'))['episodes']

filtered_ids = [episode['episode_id'] for episode in episodes if episode['object_category'] == 'cup' and episode['start_recep_category'] == 'counter']
```

and then evaluating by passing in these ids:

`python projects/habitat_ovmm/eval_baselines_agent.py <other options> habitat.dataset.episode_ids=['1','2']`

**Comment by cxzohain** [comment]
I am trying to use some receptacles that are already present in the scenes but not used in the provided episodes data. E.g. in the scene `104348328_171513363` the `bed` is present but there is no episode which have `bed` as `start_receptacle` or `goal_receptacle` for this scene. How can I generate such episode?

**Comment by yvsriram** [comment]
Got it. Please check out the config file I shared above: https://github.com/facebookresearch/habitat-lab/blob/ovmm_main_merge/habitat-lab/habitat/datasets/rearrange/configs/ovmm_val.yaml (or ovmm_train.yaml).

First, restrict the `scene_sets` to a single scene. Then, update receptacle_sets to include the receptacles of interest. For this, you can filter receptacle names by category using this mapping: https://huggingface.co/datasets/ai-habitat/OVMM_objects/blob/main/hssd-receptacles.csv. For example, for bed include all substrings like "0081c522ffe7910c701191c44b0f797a69a8548a"

**Comment by yvsriram** [comment]
Close the issue. Feel free to let us know if you have more questions.

**Comment by WhyxyxIsNotAnAvailableName** [comment]
> To generate new episodes:
> 
> You can use the episode generator script: https://github.com/facebookresearch/habitat-lab/tree/ovmm_main_merge/habitat-lab/habitat/datasets/rearrange


Hello, @yvsriram!
First of all, I would like to express my sincere gratitude for your impressive work!
I want to conduct DDPPO training using my own scene files and object files entirely. Could you please guide me on how to do this? Is there any detailed tutorial or example available? Since Habitat uses a recursive config setup, the entire task seems rather complex and confusing.

By the way, the episode generator script you mentioned earlier: [https://github.com/facebookresearch/habitat-lab/tree/ovmm_main_merge/habitat-lab/habitat/datasets/rearrange](https://github.com/facebookresearch/habitat-lab/tree/ovmm_main_merge/habitat-lab/habitat/datasets/rearrange), is no longer accessible. It shows "404 - page not found".

**Comment by yvsriram** [comment]
Thanks for the issue! Yes that branch got deleted. Please replace ovmm_main_merge with ovmm_v0.2.5 in the link
